import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Himalayan Basmati",
    description: "Aromatic long-grain rice with delicate flavor and fluffy texture. Perfect for biryanis and pilafs.",
    price: 24.99,
    originalPrice: 29.99,
    image: "/basmati-rice-grains-in-elegant-bowl.jpg",
    images: ["/basmati-rice-grains-in-elegant-bowl.jpg", "/premium-rice-grains-in-wooden-bowl-on-natural-back.jpg"],
    category: "basmati",
    badge: "Best Seller",
    inStock: true,
    weight: "2 lbs",
    origin: "Himalayan Foothills, India",
    grainType: "long",
    cookingTime: 18,
    nutritionFacts: {
      calories: 205,
      protein: 4.3,
      carbs: 45,
      fiber: 0.6,
    },
    features: ["Aged for 2 years", "Extra long grain", "Naturally aromatic", "Gluten-free"],
  },
  {
    id: 2,
    name: "Japanese Short Grain",
    description: "Premium short-grain rice perfect for sushi, onigiri, and traditional Japanese dishes.",
    price: 32.99,
    image: "/japanese-short-grain-rice-in-wooden-bowl.jpg",
    images: [
      "/japanese-short-grain-rice-in-wooden-bowl.jpg",
      "/premium-rice-grains-in-wooden-bowl-on-natural-back.jpg",
    ],
    category: "japanese",
    badge: "Premium",
    inStock: true,
    weight: "2 lbs",
    origin: "Niigata Prefecture, Japan",
    grainType: "short",
    cookingTime: 20,
    nutritionFacts: {
      calories: 242,
      protein: 4.4,
      carbs: 53,
      fiber: 0.4,
    },
    features: ["Sticky texture", "Sweet flavor", "Perfect for sushi", "Premium grade"],
  },
  {
    id: 3,
    name: "Wild Rice Blend",
    description: "Nutritious mix of wild and brown rice with nutty flavor and chewy texture.",
    price: 19.99,
    image: "/wild-rice-blend-in-rustic-bowl.jpg",
    images: ["/wild-rice-blend-in-rustic-bowl.jpg", "/premium-rice-grains-in-wooden-bowl-on-natural-back.jpg"],
    category: "wild",
    badge: "Organic",
    inStock: true,
    weight: "1.5 lbs",
    origin: "Minnesota, USA",
    grainType: "long",
    cookingTime: 45,
    nutritionFacts: {
      calories: 166,
      protein: 6.5,
      carbs: 35,
      fiber: 3,
    },
    features: ["High in protein", "Rich in antioxidants", "Organic certified", "Gluten-free"],
  },
  {
    id: 4,
    name: "Thai Jasmine Rice",
    description: "Fragrant long-grain rice with subtle floral aroma and soft, slightly sticky texture.",
    price: 21.99,
    image: "/premium-rice-grains-in-wooden-bowl-on-natural-back.jpg",
    images: ["/premium-rice-grains-in-wooden-bowl-on-natural-back.jpg", "/basmati-rice-grains-in-elegant-bowl.jpg"],
    category: "jasmine",
    badge: "Aromatic",
    inStock: true,
    weight: "2 lbs",
    origin: "Chiang Mai, Thailand",
    grainType: "long",
    cookingTime: 15,
    nutritionFacts: {
      calories: 205,
      protein: 4.3,
      carbs: 45,
      fiber: 0.6,
    },
    features: ["Naturally fragrant", "Soft texture", "Quick cooking", "Traditional variety"],
  },
  {
    id: 5,
    name: "Italian Arborio Rice",
    description: "Creamy short-grain rice perfect for risotto with excellent starch content.",
    price: 28.99,
    image: "/japanese-short-grain-rice-in-wooden-bowl.jpg",
    images: [
      "/japanese-short-grain-rice-in-wooden-bowl.jpg",
      "/premium-rice-grains-in-wooden-bowl-on-natural-back.jpg",
    ],
    category: "arborio",
    badge: "Chef's Choice",
    inStock: true,
    weight: "2 lbs",
    origin: "Piedmont, Italy",
    grainType: "short",
    cookingTime: 25,
    nutritionFacts: {
      calories: 242,
      protein: 4.4,
      carbs: 53,
      fiber: 0.4,
    },
    features: ["High starch content", "Creamy texture", "Perfect for risotto", "Premium Italian"],
  },
  {
    id: 6,
    name: "Brown Basmati Rice",
    description: "Whole grain basmati rice with nutty flavor and higher nutritional value.",
    price: 26.99,
    image: "/wild-rice-blend-in-rustic-bowl.jpg",
    images: ["/wild-rice-blend-in-rustic-bowl.jpg", "/premium-rice-grains-in-wooden-bowl-on-natural-back.jpg"],
    category: "brown",
    badge: "Healthy Choice",
    inStock: true,
    weight: "2 lbs",
    origin: "Punjab, India",
    grainType: "long",
    cookingTime: 35,
    nutritionFacts: {
      calories: 216,
      protein: 5,
      carbs: 45,
      fiber: 3.5,
    },
    features: ["Whole grain", "High fiber", "Nutty flavor", "Rich in nutrients"],
  },
]

export const categories = [
  { id: "all", name: "All Rice", count: products.length },
  { id: "basmati", name: "Basmati", count: products.filter((p) => p.category === "basmati").length },
  { id: "jasmine", name: "Jasmine", count: products.filter((p) => p.category === "jasmine").length },
  { id: "japanese", name: "Japanese", count: products.filter((p) => p.category === "japanese").length },
  { id: "wild", name: "Wild Rice", count: products.filter((p) => p.category === "wild").length },
  { id: "arborio", name: "Arborio", count: products.filter((p) => p.category === "arborio").length },
  { id: "brown", name: "Brown Rice", count: products.filter((p) => p.category === "brown").length },
]
